/**
 * SkillSync AI — RAG Curriculum Grounding Engine
 * Retrieves verified textbook passages and lecture notes from university benchmarks.
 */

export interface CurriculumPassage {
  id: string;
  subject: string;
  topic: string;
  source: string;
  edition: string;
  chapter: string;
  pageRange: string;
  text: string;
  keyRuleOrFormula?: string;
  pedagogicalTakeaway: string;
}

export const CURRICULUM_KNOWLEDGE_BASE: CurriculumPassage[] = [
  // --- MATHEMATICS (Algebra & Quadratics) ---
  {
    id: "math_fact_1",
    subject: "Mathematics",
    topic: "Factorisation",
    source: "NCERT Mathematics Class 10",
    edition: "National Council of Educational Research & Training",
    chapter: "Chapter 4: Quadratic Equations & Polynomials",
    pageRange: "pp. 72-76",
    text: "Factorisation of quadratic trinomials ax² + bx + c consists of finding two integers p and q such that p + q = b and p · q = ac. When a = 1, the expression x² + bx + c is expressed as (x + p)(x + q). Any common numerical factor across terms must always be extracted prior to middle-term decomposition.",
    keyRuleOrFormula: "x² + (p + q)x + pq = (x + p)(x + q)",
    pedagogicalTakeaway: "Always check for a Greatest Common Factor (GCF) before attempting quadratic splitting.",
  },
  {
    id: "math_quad_1",
    subject: "Mathematics",
    topic: "Quadratic Equations",
    source: "Higher Algebra by Hall & Knight",
    edition: "Classic Academic Edition",
    chapter: "Chapter 12: Theory of Quadratic Equations",
    pageRange: "pp. 115-120",
    text: "The roots of ax² + bx + c = 0 are given by x = (-b ± √(b² - 4ac)) / (2a). The discriminant Δ = b² - 4ac determines root nature: Δ > 0 implies two distinct real roots; Δ = 0 implies a single repeated rational root; Δ < 0 implies conjugate complex roots.",
    keyRuleOrFormula: "Δ = b² - 4ac, x = (-b ± √Δ)/(2a)",
    pedagogicalTakeaway: "The discriminant indicates the intersection count with the x-axis on the Cartesian plane.",
  },

  // --- OPERATING SYSTEMS ---
  {
    id: "os_sched_1",
    subject: "Operating Systems",
    topic: "Process Scheduling",
    source: "Operating System Concepts (Silberschatz, Galvin & Gagne)",
    edition: "10th Edition (Wiley)",
    chapter: "Chapter 5: CPU Scheduling",
    pageRange: "pp. 205-218",
    text: "CPU scheduling selects from among the processes in ready memory and allocates the CPU core to one of them. Preemptive scheduling occurs when a process switches from running to ready state or from waiting to ready state. Key evaluation criteria include CPU utilization, throughput, turnaround time, waiting time, and response time. Round Robin (RR) with a small time quantum approaches processor sharing but incurs context switch overhead.",
    keyRuleOrFormula: "Turnaround Time = Completion Time - Arrival Time; Waiting Time = Turnaround Time - Burst Time",
    pedagogicalTakeaway: "Shorter quantum improves responsiveness but increases context-switching overhead.",
  },
  {
    id: "os_deadlock_1",
    subject: "Operating Systems",
    topic: "Deadlocks",
    source: "Operating System Concepts (Silberschatz, Galvin & Gagne)",
    edition: "10th Edition (Wiley)",
    chapter: "Chapter 8: Deadlocks",
    pageRange: "pp. 319-338",
    text: "A deadlock state occurs if and only if four Coffman conditions hold simultaneously: Mutual Exclusion, Hold and Wait, No Preemption, and Circular Wait. Dijkstra's Banker's Algorithm prevents deadlock by maintaining a system in a safe state where a safe sequence exists for process completion.",
    keyRuleOrFormula: "Need[i][j] = Max[i][j] - Allocation[i][j]; Safe Sequence Check",
    pedagogicalTakeaway: "Deadlock prevention eliminates at least one Coffman condition; deadlock avoidance evaluates dynamic state transitions.",
  },
  {
    id: "os_vm_1",
    subject: "Operating Systems",
    topic: "Virtual Memory & Paging",
    source: "Modern Operating Systems (Andrew S. Tanenbaum)",
    edition: "4th Edition (Pearson)",
    chapter: "Chapter 3: Memory Management",
    pageRange: "pp. 183-204",
    text: "Virtual memory maps virtual addresses generated by the CPU to physical memory addresses via the Memory Management Unit (MMU) using page tables. When a page is accessed that is not in main memory, a page fault occurs. Page replacement algorithms include FIFO, Optimal (Belady's), and Least Recently Used (LRU). FIFO suffers from Belady's Anomaly where adding frames increases page faults.",
    keyRuleOrFormula: "Virtual Address = Page Number (p) + Offset (d); Physical Address = Frame Number (f) + Offset (d)",
    pedagogicalTakeaway: "LRU page replacement approximates optimal behavior by using past access history as a predictor.",
  },

  // --- COMPUTER NETWORKS ---
  {
    id: "cn_osi_1",
    subject: "Computer Networks",
    topic: "OSI & TCP/IP Models",
    source: "Computer Networking: A Top-Down Approach (Kurose & Ross)",
    edition: "8th Edition (Pearson)",
    chapter: "Chapter 1: Computer Networks and the Internet",
    pageRange: "pp. 48-62",
    text: "Protocol layering decomposes network functionality into hierarchical layers. The 5-layer Internet protocol stack consists of Application (HTTP, DNS), Transport (TCP, UDP), Network (IP, ICMP), Link (Ethernet, Wi-Fi), and Physical. Encapsulation wraps headers around payloads at each successive lower layer.",
    keyRuleOrFormula: "Data Unit Names: Application = Message, Transport = Segment, Network = Datagram/Packet, Link = Frame",
    pedagogicalTakeaway: "Each layer provides services to the layer above while hiding implementation details.",
  },
  {
    id: "cn_tcp_1",
    subject: "Computer Networks",
    topic: "TCP Flow & Congestion Control",
    source: "Computer Networking: A Top-Down Approach (Kurose & Ross)",
    edition: "8th Edition (Pearson)",
    chapter: "Chapter 3: Transport Layer",
    pageRange: "pp. 235-265",
    text: "TCP provides connection-oriented, reliable byte-stream transfer via a three-way handshake (SYN, SYN-ACK, ACK). Flow control prevents a fast sender from overwhelming a slow receiver using the Receive Window (rwnd). Congestion control prevents network saturation through Slow Start, Congestion Avoidance, Fast Retransmit (3 duplicate ACKs), and Fast Recovery.",
    keyRuleOrFormula: "Effective Window = min(Congestion Window cwnd, Receive Window rwnd)",
    pedagogicalTakeaway: "AIMD (Additive Increase, Multiplicative Decrease) ensures convergence to bandwidth fairness.",
  },
  {
    id: "cn_subnet_1",
    subject: "Computer Networks",
    topic: "IP Addressing & Subnetting",
    source: "TCP/IP Illustrated, Volume 1 (W. Richard Stevens)",
    edition: "2nd Edition (Addison-Wesley)",
    chapter: "Chapter 2: The Internet Address Architecture",
    pageRange: "pp. 35-54",
    text: "CIDR (Classless Inter-Domain Routing) uses a prefix length /n to divide an IPv4 address into network and host portions. The subnet mask has n leading 1s. The number of usable host addresses in a subnet with host bits h = 32 - n is 2^h - 2 (subtracting the network identifier and broadcast address).",
    keyRuleOrFormula: "Usable Hosts = 2^(32 - prefix) - 2",
    pedagogicalTakeaway: "The first address is reserved for Network ID and the last address is the Directed Broadcast address.",
  },

  // --- DATA STRUCTURES & ALGORITHMS ---
  {
    id: "dsa_dp_1",
    subject: "Data Structures & Algorithms",
    topic: "Dynamic Programming",
    source: "Introduction to Algorithms (CLRS: Cormen, Leiserson, Rivest, Stein)",
    edition: "4th Edition (MIT Press)",
    chapter: "Chapter 14: Dynamic Programming",
    pageRange: "pp. 383-412",
    text: "Dynamic programming applies when subproblems overlap and the problem possesses optimal substructure: an optimal solution to the problem contains optimal solutions to subproblems. Two paradigms exist: Top-down with Memoization (caching recursive call results) and Bottom-up with Tabulation (filling a DP table iteratively starting from base cases).",
    keyRuleOrFormula: "0/1 Knapsack: dp[i][w] = max(dp[i-1][w], val[i-1] + dp[i-1][w - wt[i-1]])",
    pedagogicalTakeaway: "Identify the state space, transition recurrence, and base conditions before implementing.",
  },
  {
    id: "dsa_graphs_1",
    subject: "Data Structures & Algorithms",
    topic: "Graph Algorithms",
    source: "Introduction to Algorithms (CLRS: Cormen, Leiserson, Rivest, Stein)",
    edition: "4th Edition (MIT Press)",
    chapter: "Chapter 20: Elementary Graph Algorithms",
    pageRange: "pp. 589-612",
    text: "Breadth-First Search (BFS) explores all vertices at distance k before vertices at distance k+1 using a FIFO queue, discovering shortest paths in unweighted graphs with time complexity O(V + E). Depth-First Search (DFS) explores vertices deeply using recursion or a LIFO stack, classifying edges into tree, back, forward, and cross edges.",
    keyRuleOrFormula: "Time: O(V + E) with Adjacency List; O(V²) with Adjacency Matrix",
    pedagogicalTakeaway: "A directed graph is acyclic (DAG) if and only if a DFS yields no back edges.",
  },
  {
    id: "dsa_trees_1",
    subject: "Data Structures & Algorithms",
    topic: "Binary Search Trees",
    source: "Algorithms (Robert Sedgewick & Kevin Wayne)",
    edition: "4th Edition (Addison-Wesley)",
    chapter: "Chapter 3: Searching",
    pageRange: "pp. 396-421",
    text: "A Binary Search Tree (BST) maintains the invariant that for every node x, keys in x's left subtree are strictly smaller than x.key, and keys in x's right subtree are strictly greater. Inorder traversal of a BST visits keys in monotonically increasing sorted order. Average time for search, insertion, and deletion is O(log n), but degrades to O(n) if unbalanced.",
    keyRuleOrFormula: "Inorder(BST) = Sorted Array; Height: log n (balanced) to n (skewed)",
    pedagogicalTakeaway: "Balanced variants (AVL, Red-Black Trees) guarantee O(log n) worst-case time by rotating nodes.",
  },
];

/**
 * Retrieves the most relevant curriculum passage for a topic and student prompt.
 */
export function retrieveCurriculumPassages(
  query: string,
  subject?: string,
  topic?: string
): CurriculumPassage[] {
  const queryLower = query.toLowerCase();
  const topicLower = (topic || "").toLowerCase();
  const subjectLower = (subject || "").toLowerCase();

  // Score each passage by relevance
  const scored = CURRICULUM_KNOWLEDGE_BASE.map(passage => {
    let score = 0;

    // Exact topic match
    if (topic && passage.topic.toLowerCase() === topicLower) {
      score += 10;
    } else if (topic && passage.topic.toLowerCase().includes(topicLower)) {
      score += 6;
    }

    // Subject match
    if (subject && passage.subject.toLowerCase() === subjectLower) {
      score += 4;
    }

    // Query keyword overlap
    const terms = queryLower.split(/\W+/).filter(w => w.length > 2);
    for (const term of terms) {
      if (passage.text.toLowerCase().includes(term)) score += 2;
      if (passage.topic.toLowerCase().includes(term)) score += 3;
      if (passage.keyRuleOrFormula?.toLowerCase().includes(term)) score += 3;
    }

    return { passage, score };
  });

  scored.sort((a, b) => b.score - a.score);

  // Return top 2 passages or topic match
  const filtered = scored.filter(s => s.score > 2).map(s => s.passage);
  if (filtered.length > 0) {
    return filtered.slice(0, 2);
  }

  // Fallback to topic or first passage
  const defaultPassage = CURRICULUM_KNOWLEDGE_BASE.find(
    p => p.topic.toLowerCase() === topicLower || p.subject.toLowerCase() === subjectLower
  );
  return defaultPassage ? [defaultPassage] : [CURRICULUM_KNOWLEDGE_BASE[0]];
}
